/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReportRouteImport } from './routes/report'
import { Route as NotificationRouteImport } from './routes/notification'
import { Route as LiveCommandCenterRouteImport } from './routes/live-command-center'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AiWorkflowRouteImport } from './routes/ai-workflow'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperationsIndexRouteImport } from './routes/operations.index'
import { Route as OperationsLoginRouteImport } from './routes/operations.login'

const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationRoute = NotificationRouteImport.update({
  id: '/notification',
  path: '/notification',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveCommandCenterRoute = LiveCommandCenterRouteImport.update({
  id: '/live-command-center',
  path: '/live-command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWorkflowRoute = AiWorkflowRouteImport.update({
  id: '/ai-workflow',
  path: '/ai-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsIndexRoute = OperationsIndexRouteImport.update({
  id: '/operations/',
  path: '/operations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsLoginRoute = OperationsLoginRouteImport.update({
  id: '/operations/login',
  path: '/operations/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-workflow': typeof AiWorkflowRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/command-center': typeof CommandCenterRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/dispatch': typeof DispatchRoute
  '/incidents': typeof IncidentsRoute
  '/live-command-center': typeof LiveCommandCenterRoute
  '/notification': typeof NotificationRoute
  '/report': typeof ReportRoute
  '/resources': typeof ResourcesRoute
  '/safety': typeof SafetyRoute
  '/operations/login': typeof OperationsLoginRoute
  '/operations/': typeof OperationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-workflow': typeof AiWorkflowRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/command-center': typeof CommandCenterRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/dispatch': typeof DispatchRoute
  '/incidents': typeof IncidentsRoute
  '/live-command-center': typeof LiveCommandCenterRoute
  '/notification': typeof NotificationRoute
  '/report': typeof ReportRoute
  '/resources': typeof ResourcesRoute
  '/safety': typeof SafetyRoute
  '/operations/login': typeof OperationsLoginRoute
  '/operations': typeof OperationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-workflow': typeof AiWorkflowRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/command-center': typeof CommandCenterRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/dispatch': typeof DispatchRoute
  '/incidents': typeof IncidentsRoute
  '/live-command-center': typeof LiveCommandCenterRoute
  '/notification': typeof NotificationRoute
  '/report': typeof ReportRoute
  '/resources': typeof ResourcesRoute
  '/safety': typeof SafetyRoute
  '/operations/login': typeof OperationsLoginRoute
  '/operations/': typeof OperationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-workflow'
    | '/alerts'
    | '/analytics'
    | '/command-center'
    | '/contacts'
    | '/dashboard'
    | '/dispatch'
    | '/incidents'
    | '/live-command-center'
    | '/notification'
    | '/report'
    | '/resources'
    | '/safety'
    | '/operations/login'
    | '/operations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-workflow'
    | '/alerts'
    | '/analytics'
    | '/command-center'
    | '/contacts'
    | '/dashboard'
    | '/dispatch'
    | '/incidents'
    | '/live-command-center'
    | '/notification'
    | '/report'
    | '/resources'
    | '/safety'
    | '/operations/login'
    | '/operations'
  id:
    | '__root__'
    | '/'
    | '/ai-workflow'
    | '/alerts'
    | '/analytics'
    | '/command-center'
    | '/contacts'
    | '/dashboard'
    | '/dispatch'
    | '/incidents'
    | '/live-command-center'
    | '/notification'
    | '/report'
    | '/resources'
    | '/safety'
    | '/operations/login'
    | '/operations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiWorkflowRoute: typeof AiWorkflowRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CommandCenterRoute: typeof CommandCenterRoute
  ContactsRoute: typeof ContactsRoute
  DashboardRoute: typeof DashboardRoute
  DispatchRoute: typeof DispatchRoute
  IncidentsRoute: typeof IncidentsRoute
  LiveCommandCenterRoute: typeof LiveCommandCenterRoute
  NotificationRoute: typeof NotificationRoute
  ReportRoute: typeof ReportRoute
  ResourcesRoute: typeof ResourcesRoute
  SafetyRoute: typeof SafetyRoute
  OperationsLoginRoute: typeof OperationsLoginRoute
  OperationsIndexRoute: typeof OperationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification': {
      id: '/notification'
      path: '/notification'
      fullPath: '/notification'
      preLoaderRoute: typeof NotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-command-center': {
      id: '/live-command-center'
      path: '/live-command-center'
      fullPath: '/live-command-center'
      preLoaderRoute: typeof LiveCommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-workflow': {
      id: '/ai-workflow'
      path: '/ai-workflow'
      fullPath: '/ai-workflow'
      preLoaderRoute: typeof AiWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/': {
      id: '/operations/'
      path: '/operations'
      fullPath: '/operations/'
      preLoaderRoute: typeof OperationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/login': {
      id: '/operations/login'
      path: '/operations/login'
      fullPath: '/operations/login'
      preLoaderRoute: typeof OperationsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiWorkflowRoute: AiWorkflowRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  CommandCenterRoute: CommandCenterRoute,
  ContactsRoute: ContactsRoute,
  DashboardRoute: DashboardRoute,
  DispatchRoute: DispatchRoute,
  IncidentsRoute: IncidentsRoute,
  LiveCommandCenterRoute: LiveCommandCenterRoute,
  NotificationRoute: NotificationRoute,
  ReportRoute: ReportRoute,
  ResourcesRoute: ResourcesRoute,
  SafetyRoute: SafetyRoute,
  OperationsLoginRoute: OperationsLoginRoute,
  OperationsIndexRoute: OperationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
